language: android
jdk: oraclejdk8
android:
        components:
                - build-tools-25.0.2
                - android-22
                - platform-tools
                - tools
                - extra-android-support
                - extra-android-m2repository

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGhhbGxvZ2FsbG8lM0FtYXRyaXgub3JnLyUyMWF1WEZqanl1SUJxWFZXdVNtTiUzQW1hdHJpeC5vcmc"
        on_success: always  # always|never|change
        on_failure: always
        on_start: never

script:
  - ./gradlew assembleDebug

licenses:
        - 'android-sdk-license-.+' 
