language: android
jdk: oraclejdk8
sudo: required
android:
        components:
                - build-tools-25.0.2
                - build-tools-25.0.0
                - android-22
                - android-25
                - platform-tools
                - tools
                - extra-android-support
                - extra-android-m2repository

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGhhbGxvZ2FsbG8lM0FtYXRyaXgub3JnLyUyMWF1WEZqanl1SUJxWFZXdVNtTiUzQW1hdHJpeC5vcmc"
        on_success: always  # always|never|change
        on_failure: always
        on_start: never

script:
  - ./gradlew assembleDebug

before_script:
  - sudo cp ./android-sdk-license /usr/local/android-sdk/licenses/android-sdk-license
